title: Awesome title
author: Andrew Greene
email: andrewigreene@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Awesome description for my new site. Naming things are hard.
theme: minima

# social links
twitter_username: aig79 # DO NOT include the @ character, or else the build will fail!
github_username:  aig79 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
